import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        chakra: ['var(--font-chakra)'],
        sora: ['var(--font-sora)'],
        barlow: ['var(--font-barlow)'],
        batgrexo: ['var(--font-batgrexo)'],
        impact: ['var(--font-impact)'],
        "lexend-giga": "var(--font-lexend-giga)",
      },
      colors: {
        'main-green': '#1CBBBB',
        'main-blue1': '#86DEFE',
        'main-blue2': '#7BB5FC',
        'main-gray1': '#929292',
        'main-red1': '#F77E1E',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primary: {
          DEFAULT: "#32E5EB",
          "50": "#D9FAFB",
          "100": "#C7F8F9",
          "200": "#A2F3F6",
          "300": "#7DEEF2",
          "400": "#57E9EE",
          "500": "#32E5EB",
          "600": "#15CAD0",
          "700": "#10999D",
          "800": "#0B676A",
          "900": "#053537",
        },
        secondary: {
          DEFAULT: "#6628C5",
          50: "#8C68E0",
          100: "#8760DF",
          200: "#7D4FDB",
          300: "#743ED8",
          400: "#6B2DD4",
          500: "#6628C5",
          600: "#55209F",
          700: "#431979",
          800: "#2F1153",
          900: "#1A092C",
          950: "#0F0519",
        },
        violet: {
          DEFAULT: "#5F188B",
          400: "#71319D",
          500: "#5F188B",
          600: "#471B62",
        },
        'gunnies-purple': '#5865F2',
        "gunnies-dark-1": '#111928',
        "gunnies-dark-2": '#1F2A37',
      },
    },
    backgroundImage: {
      'ic-3lines': "url('/assets/icons/ic-3-lines.svg')",
      'ic-close': "url('/assets/icons/ic-close.svg')",
      'ic-next': "url('/assets/icons/ic-next.svg')",
      'ic-next-hover': "url('/assets/icons/ic-next-hover.svg')",
      'ic-prev': "url('/assets/icons/ic-prev.svg')",
      'ic-prev-hover': "url('/assets/icons/ic-prev-hover.svg')",
      'ic-close-black': "url('/assets/icons/ic-close-black.svg')",
      'gunnies-logo-hz': "url('/images/gunnies-logo-hz.svg')",
      'img-banner': "url('/images/banner.png')",
      'lineup-and-more-bg': "url('/images/lineup-and-more/lineup-and-more-bg.webp')",
      'lineup-and-more-bg-md': "url('/images/lineup-and-more/lineup-and-more-bg-md.webp')",
      'img-character-1': "url('/images/lineup-and-more/img-character-1.webp')",
      'img-character-1-md': "url('/images/lineup-and-more/img-character-1-md.webp')",
      'img-character-1-bg': "url('/images/lineup-and-more/img-character-1-bg.webp')",
      'img-character-1-bg-md': "url('/images/lineup-and-more/img-character-1-bg-md.webp')",
      'img-character-2': "url('/images/lineup-and-more/img-character-2.webp')",
      'img-character-2-md': "url('/images/lineup-and-more/img-character-2-md.webp')",
      'img-character-2-bg': "url('/images/lineup-and-more/img-character-2-bg.webp')",
      'img-character-2-bg-md': "url('/images/lineup-and-more/img-character-2-bg-md.webp')",
      'img-character-3': "url('/images/lineup-and-more/img-character-3.webp')",
      'img-character-3-md': "url('/images/lineup-and-more/img-character-3-md.webp')",
      'img-character-3-bg': "url('/images/lineup-and-more/img-character-3-bg.webp')",
      'img-character-3-bg-md': "url('/images/lineup-and-more/img-character-3-bg-md.webp')",
      'img-character-4': "url('/images/lineup-and-more/img-character-4.webp')",
      'img-character-4-md': "url('/images/lineup-and-more/img-character-4-md.webp')",
      'img-character-4-bg': "url('/images/lineup-and-more/img-character-4-bg.webp')",
      'img-character-4-bg-md': "url('/images/lineup-and-more/img-character-4-bg-md.webp')",
      'img-character-5': "url('/images/lineup-and-more/img-character-5.webp')",
      'img-character-5-md': "url('/images/lineup-and-more/img-character-5-md.webp')",
      'img-character-5-bg': "url('/images/lineup-and-more/img-character-5-bg.webp')",
      'img-character-5-bg-md': "url('/images/lineup-and-more/img-character-5-bg-md.webp')",
      'img-character-6': "url('/images/lineup-and-more/img-character-6.webp')",
      'img-character-6-md': "url('/images/lineup-and-more/img-character-6-md.webp')",
      'img-character-6-bg': "url('/images/lineup-and-more/img-character-6-bg.webp')",
      'img-character-6-bg-md': "url('/images/lineup-and-more/img-character-6-bg-md.webp')",
      'img-character-7': "url('/images/lineup-and-more/img-character-7.webp')",
      'img-character-7-md': "url('/images/lineup-and-more/img-character-7-md.webp')",
      'img-character-7-bg': "url('/images/lineup-and-more/img-character-7-bg.webp')",
      'img-character-7-bg-md': "url('/images/lineup-and-more/img-character-7-bg-md.webp')",
      'ic-character-1': "url('/images/lineup-and-more/ic-character-1.webp')",
      'ic-character-2': "url('/images/lineup-and-more/ic-character-2.webp')",
      'ic-character-3': "url('/images/lineup-and-more/ic-character-3.webp')",
      'ic-character-4': "url('/images/lineup-and-more/ic-character-4.webp')",
      'ic-character-5': "url('/images/lineup-and-more/ic-character-5.webp')",
      'ic-character-6': "url('/images/lineup-and-more/ic-character-6.webp')",
      'ic-character-7': "url('/images/lineup-and-more/ic-character-7.webp')",
      'ic-chapter-1': "url('/images/lineup-and-more/ic-chapter-1.webp')",
      'ic-chapter-2': "url('/images/lineup-and-more/ic-chapter-2.webp')",
      'ic-chapter-3': "url('/images/lineup-and-more/ic-chapter-3.webp')",
      'ic-chapter-4': "url('/images/lineup-and-more/ic-chapter-4.webp')",
      'ic-chapter-5': "url('/images/lineup-and-more/ic-chapter-5.webp')",
      'img-chapter-1': "url('/images/lineup-and-more/img-chapter-1.webp')",
      'img-chapter-2': "url('/images/lineup-and-more/img-chapter-2.webp')",
      'img-chapter-3': "url('/images/lineup-and-more/img-chapter-3.webp')",
      'img-chapter-4': "url('/images/lineup-and-more/img-chapter-4.webp')",
      'img-chapter-5': "url('/images/lineup-and-more/img-chapter-5.webp')",
    },
    screens: {
      xs: "475px",
      sm: "640px",
      md: "768px",
      lg: "1025px",
      xl: "1280px",
      '2xl': '1536px',
      '3xl': '1900px',
    },
  },
  plugins: [],
};
export default config;
