# Generated by Django 4.2.4 on 2025-05-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_paymentlog_subscriptionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lootlockerusertoken',
            name='lootlocker_player_id',
        ),
        migrations.AddField(
            model_name='lootlockerusertoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lootlocker_token', to='common.user'),
        ),
    ]
