# Generated by Django 4.2.4 on 2025-05-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_lootlockerusertoken_lootlocker_player_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_stars', to='common.user')),
            ],
            options={
                'db_table': 'user_stars',
            },
        ),
        migrations.CreateModel(
            name='ChestReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(max_length=50)),
                ('reward_value', models.IntegerField(default=0)),
                ('tx_hash', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chest_rewards', to='common.user')),
            ],
            options={
                'db_table': 'chest_rewards',
            },
        ),
        migrations.CreateModel(
            name='ChestOpenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chest_open_data', to='common.user')),
            ],
            options={
                'db_table': 'chest_open_data',
            },
        ),
    ]
