# Generated by Django 4.2.4 on 2025-05-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_userstars_chestreward_chestopendata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mm_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
