# Generated by Django 4.2.4 on 2025-05-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_user_mm_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRewardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reward_data', to='common.user')),
            ],
            options={
                'db_table': 'daily_reward_data',
            },
        ),
    ]
