# Generated by Django 4.2.4 on 2025-05-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_dailyrewarddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='steam_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_from',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
