# Generated by Django 4.2.4 on 2025-05-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_user_steam_id_user_user_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='chestopendata',
            name='chest_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chestreward',
            name='chest_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
