# Generated by Django 4.2.4 on 2025-05-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_chestopendata_chest_type_chestreward_chest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chestreward',
            name='reward_from',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
