# Generated by Django 4.2.4 on 2025-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_chestreward_reward_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lootlocker_player_ulid',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
