# Generated by Django 4.2.4 on 2025-07-09 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_user_lootlocker_player_ulid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=10)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(max_length=100, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_email', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shop_purchase_history',
            },
        ),
        migrations.CreateModel(
            name='ShopPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_product_id', models.CharField(max_length=100)),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('metadata', models.JSONField(default=dict, null=True)),
                ('lootlocker_assets_granted', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='common.shoppurchasehistory')),
            ],
            options={
                'db_table': 'shop_purchase_items',
            },
        ),
    ]
