# Generated by Django 4.2.4 on 2025-08-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_shoppurchasehistory_shoppurchaseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnChainKillTxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(blank=True, max_length=200)),
                ('count', models.IntegerField(default=1)),
                ('tx_hash', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_kill_from', to='common.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_kill_to', to='common.user')),
            ],
            options={
                'db_table': 'onchain_kill_tx_data',
            },
        ),
        migrations.CreateModel(
            name='OnChainCurrencyTxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(blank=True, max_length=20)),
                ('tx_type', models.CharField(blank=True, max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('tx_hash', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_currency_tx_data', to='common.user')),
            ],
            options={
                'db_table': 'onchain_currency_tx_data',
            },
        ),
    ]
