# Generated by Django 4.2.4 on 2025-08-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_onchainkilltxdata_onchaincurrencytxdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='epic_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
