# Generated by Django 4.2.4 on 2025-09-23 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_mission_usermission_missionreward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onchaincurrencytxdata',
            name='tx_hash',
        ),
        migrations.CreateModel(
            name='OnChainCurrencyTxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.BigIntegerField()),
                ('tx_hash', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='common.onchaincurrencytxdata')),
            ],
            options={
                'db_table': 'onchain_currency_tx_log',
                'unique_together': {('tx_data', 'chain_id')},
            },
        ),
    ]
