# Generated by Django 4.2.4 on 2025-09-23 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_remove_onchaincurrencytxdata_tx_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnChainKillSummaryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kills', models.IntegerField()),
                ('chain_id', models.BigIntegerField()),
                ('tx_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_kill_summary_logs', to='common.user')),
            ],
            options={
                'db_table': 'onchain_kill_summary_log',
            },
        ),
    ]
