# Generated by Django 4.2.4 on 2025-10-14 21:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_onchainkillsummarylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('game_type', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('completed', 'Completed')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minigame_sessions', to='common.user')),
            ],
            options={
                'db_table': 'minigame_session',
            },
        ),
    ]
