# Generated by Django 4.2.4 on 2025-10-27 13:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_minigamesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReferralDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_details', to='common.user')),
            ],
            options={
                'db_table': 'user_referral_details',
            },
        ),
        migrations.CreateModel(
            name='HiddenObjectGamePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('found', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_object_game_posters', to='common.user')),
            ],
            options={
                'db_table': 'hidden_object_game_poster',
            },
        ),
    ]
