# Generated by Django 4.2.4 on 2025-12-09 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_usermedia_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(blank=True, max_length=50)),
                ('reward_from', models.CharField(blank=True, max_length=50)),
                ('reward_value', models.IntegerField(default=0)),
                ('tx_hash', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='common.user')),
            ],
            options={
                'db_table': 'rewards',
            },
        ),
    ]
