# Generated by Django 4.2.4 on 2025-12-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='metamask_bind',
            field=models.BooleanField(null=True),
        ),
    ]
