# Generated by Django 4.2.4 on 2026-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_user_metamask_bind'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game_seasons',
            },
        ),
    ]
