# Generated by Django 4.2.4 on 2026-02-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_gameseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootlockerusertoken',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
